# Generated by Django 3.2.19 on 2023-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
