# Generated by Django 4.1.9 on 2023-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
