# Generated by Django 3.2.19 on 2023-05-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20230515_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='wieght',
            new_name='weight',
        ),
    ]
