# Generated by Django 4.1.9 on 2023-06-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leader',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
