# Generated by Django 3.2.19 on 2023-06-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='leader',
        ),
        migrations.AddField(
            model_name='record',
            name='assist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='block',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='rebound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='steal',
            field=models.IntegerField(default=0),
        ),
    ]
